version: "3"

services:
  chatbot:
    build: bot
    image: ripples/feishu-chatbot
    restart: unless-stopped
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      - LOG_LEVEL=info
      - CHATGPT_BASE_URL=http://go-chatgpt-api:8080/
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./db.json:/src/db.json

  proxy:
    build: proxy
    image: ripples/chatgpt-proxy
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /etc/localtime:/etc/localtime:ro

  go-chatgpt-api:
    image: linweiyuan/go-chatgpt-api
    environment:
      - GIN_MODE=release
      - CHATGPT_PROXY_SERVER=http://chatgpt-proxy-server:9515
      - NETWORK_PROXY_SERVER=socks5://chatgpt-proxy-server-warp:65535
    depends_on:
      - chatgpt-proxy-server
      - chatgpt-proxy-server-warp
    restart: unless-stopped

  chatgpt-proxy-server:
    image: linweiyuan/chatgpt-proxy-server
    restart: unless-stopped

  chatgpt-proxy-server-warp:
    image: linweiyuan/chatgpt-proxy-server-warp
    restart: unless-stopped
