version: "3"

services:
  chatbot:
    build: bot
    image: ripples/feishu-chatbot
    restart: unless-stopped
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      - LOG_LEVEL=info
      - CHATGPT_BASE_URL=http://proxy:8080/api/
    depends_on:
      - proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./db.json:/src/db.json

  proxy:
    build: proxy
    image: ripples/chatgpt-proxy
    restart: unless-stopped
    env_file:
      - .env
